---
format: 
  html:
    include-in-header: 
      - includes/icons.html
---

## [Research]{style="color: #1E354B"}

#### [Area of Focus]{style="color: #7f7f7f"}

The CVmedLab is focused on studying cardiovascular effects of common chronic diseases (hypertension, type 2 diabetes, thromboembolic disorders) and optimizing drug therapy to minimize risks of these diseases.

A major focus is on adverse effects of chronic **uncontrolled blood pressure (hypertension)** and ways to optimize antihypertensive drug therapy to mitigate these adverse effects. We have particular expertise in the area of **treatment-resistant hypertension**.

#### [Methods]{style="color: #7f7f7f"}

Our research spans population and clinical sciences related to cardiovascular disease and its treatment. This includes both observational research, as well as clinical trial work, primarily through my collaboration with colleagues in the [Division of Cardiovascular Medicine](https://cardiology.medicine.ufl.edu/).

We are also interested in methodologic research for using electronic health record (EHR) data, including how to minimize misclassification when measuring longitudinal drug exposure from EHR prescribing data, and methods for dealing with missingness in EHR data and biases associated with missing data.

#### [Funding]{style="color: #7f7f7f"}

Current funding for the lab is through the [National Heart, Lung and Blood Institute (NHLBI)](https://www.nhlbi.nih.gov/) via our work on optimizing antihypertensive drug selection ([K01 HL138172](https://projectreporter.nih.gov/project_info_description.cfm?aid=9744791&icde=49548436)), high-throughput screening for antihypertensive prescribing cascades ([R21 HL159576](https://reporter.nih.gov/search/aVEJuvDVJU--RrP-s2UzIQ/project-details/10516334)), evaluating blood pressure-lowering mechanisms of minocycline in resistant hypertension ([2R01 HL132448-05](https://reporter.nih.gov/search/mzMxvRahg0uAVAQBSjXSrg/project-details/10801613)), and evaluating use of telehealth and self-monitoring of blood pressure since the pandemic ([R01 HL171387](https://reporter.nih.gov/search/wl5Y2Isx9UaJOTs935-VyA/project-details/11048727)). Dr. Smith is also the pharmacy lead for the [Women's IschemiA TRial to Reduce Events In Non-ObstRuctive CAD (WARRIOR)](https://clinicaltrials.gov/ct2/show/NCT03417388) trial.

#### [Publications]{style="color: #7f7f7f"}

A complete list of my lab's journal publications can be found on [PubMed](https://www.ncbi.nlm.nih.gov/myncbi/steven.smith.4/bibliography/public/) or [Google Scholar](https://scholar.google.com/citations?user=3MKlN-EAAAAJ&hl=en). Newer publications are also available via [ORCID](https://orcid.org/0000-0002-0201-839X). We provide pdfs of most of our pubs, but if for some reason you cannot access the link, or a particular journal, please [email me](mailto:ssmith@cop.ufl.edu) for an author's print.
